import defaultTheme from "tailwindcss/defaultTheme";
import forms from "@tailwindcss/forms";
import typography from "@tailwindcss/typography";

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./vendor/laravel/jetstream/**/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/views/**/*.blade.php",
        "./resources/js/**/*.vue",
        "./resources/js/**/*.js",
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ["Figtree", ...defaultTheme.fontFamily.sans],
            },
            colors: {
                text: {
                    DEFAULT: "var(--text-default)",
                    50: "var(--text-50)",
                    100: "var(--text-100)",
                    200: "var(--text-200)",
                    300: "var(--text-300)",
                    400: "var(--text-400)",
                    500: "var(--text-500)",
                    600: "var(--text-600)",
                    700: "var(--text-700)",
                    800: "var(--text-800)",
                    900: "var(--text-900)",
                    950: "var(--text-950)",
                },
                background: {
                    DEFAULT: "var(--background-default)",
                    50: "var(--background-50)",
                    100: "var(--background-100)",
                    200: "var(--background-200)",
                    300: "var(--background-300)",
                    400: "var(--background-400)",
                    500: "var(--background-500)",
                    600: "var(--background-600)",
                    700: "var(--background-700)",
                    800: "var(--background-800)",
                    900: "var(--background-900)",
                    950: "var(--background-950)",
                },
                primary: {
                    DEFAULT: "var(--primary-default)",
                    50: "var(--primary-50)",
                    100: "var(--primary-100)",
                    200: "var(--primary-200)",
                    300: "var(--primary-300)",
                    400: "var(--primary-400)",
                    500: "var(--primary-500)",
                    600: "var(--primary-600)",
                    700: "var(--primary-700)",
                    800: "var(--primary-800)",
                    900: "var(--primary-900)",
                    950: "var(--primary-950)",
                },
                secondary: {
                    DEFAULT: "var(--secondary-default)",
                    50: "var(--secondary-50)",
                    100: "var(--secondary-100)",
                    200: "var(--secondary-200)",
                    300: "var(--secondary-300)",
                    400: "var(--secondary-400)",
                    500: "var(--secondary-500)",
                    600: "var(--secondary-600)",
                    700: "var(--secondary-700)",
                    800: "var(--secondary-800)",
                    900: "var(--secondary-900)",
                    950: "var(--secondary-950)",
                },
                accent: {
                    DEFAULT: "var(--accent-default)",
                    50: "var(--accent-50)",
                    100: "var(--accent-100)",
                    200: "var(--accent-200)",
                    300: "var(--accent-300)",
                    400: "var(--accent-400)",
                    500: "var(--accent-500)",
                    600: "var(--accent-600)",
                    700: "var(--accent-700)",
                    800: "var(--accent-800)",
                    900: "var(--accent-900)",
                    950: "var(--accent-950)",
                },
                success: {
                    DEFAULT: "var(--success-default)",
                    50: "var(--success-50)",
                    100: "var(--success-100)",
                    200: "var(--success-200)",
                    300: "var(--success-300)",
                    400: "var(--success-400)",
                    500: "var(--success-500)",
                    600: "var(--success-600)",
                    700: "var(--success-700)",
                    800: "var(--success-800)",
                    900: "var(--success-900)",
                    950: "var(--success-950)",
                },

                danger: {
                    DEFAULT: "var(--danger-default)",
                    50: "var(--danger-50)",
                    100: "var(--danger-100)",
                    200: "var(--danger-200)",
                    300: "var(--danger-300)",
                    400: "var(--danger-400)",
                    500: "var(--danger-500)",
                    600: "var(--danger-600)",
                    700: "var(--danger-700)",
                    800: "var(--danger-800)",
                    900: "var(--danger-900)",
                    950: "var(--danger-950)",
                },
                warning: {
                    DEFAULT: "var(--warning-default)",
                    50: "var(--warning-50)",
                    100: "var(--warning-100)",
                    200: "var(--warning-200)",
                    300: "var(--warning-300)",
                    400: "var(--warning-400)",
                    500: "var(--warning-500)",
                    600: "var(--warning-600)",
                    700: "var(--warning-700)",
                    800: "var(--warning-800)",
                    900: "var(--warning-900)",
                    950: "var(--warning-950)",
                },
                info: {
                    DEFAULT: "var(--info-default)",
                    50: "var(--info-50)",
                    100: "var(--info-100)",
                    200: "var(--info-200)",
                    300: "var(--info-300)",
                    400: "var(--info-400)",
                    500: "var(--info-500)",
                    600: "var(--info-600)",
                    700: "var(--info-700)",
                    800: "var(--info-800)",
                    900: "var(--info-900)",
                    950: "var(--info-950)",
                },
            },
        },
    },

    plugins: [forms, typography],
};
